### PR TITLE
Convert measurement

### PR DESCRIPTION
**Pull request by elbracht**
Hello,

I created functions for converting range and weight. I mainly took the development of our italian or brazilian portoguese friends and adapted it to our converter.

Should users be able to turn on this feature in settings?

Issue: #7

### CODE REVIEW

**Comment by Fallayn** [comment]
Hey! Sorry I took a bit to respond. Thanks for your contribution!

Yes, having a setting for this would be nice. Otherwise, this looks good at a first glance. :)

**Comment by elbracht** [comment]
I have added the settings for range and weight.


I noticed one more problem: The weight of the items is adjusted, but not the total weight that the character can carry. I don't know exactly what the total weight is based on or how to change it.

Screenshot 2021-08-19 at 10 54 09

**Comment by elbracht** [comment]
I saw that there is a setting in Foundry to switch to the metric system. The setting fixes the problem described before, because it halves the total weight that the character can carry.

Screenshot 2021-08-23 at 14 44 39

**Comment by Fallayn** [comment]
I'll see if I can find where that is defined

**Comment by elbracht** [comment]
@Fallayn I'm not sure if we can / need to adjust the total weight. The weight can be adjusted via the Foundry settings and is not present in the Italian or Brazilian Portuguese repos.

**Comment by Fallayn** [comment]
Thank you for helping out and contributing this! 🔥

**Comment by Fallayn** [comment]
FYI: I changed the weight translation to use the core system setting instead, so if you enable metric units for weight in the system settings, your converter is automatically used: https://github.com/League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de/commit/a95ab87920a9897875fbdcab3a9b552e72c5d2e2

Thanks again!

**Pull request merged**
